using System;
using System.Collections.Generic;

using Headway.WorkflowEngine.Exceptions;

namespace Headway.WorkflowEngine
{
    /// <summary>
    /// Encapsulates information about a workflow that is generated by calling
    /// the <see cref="Workflow.Analyze"/> method, which looks for consistency
    /// errors and gathers counts on the number of nodes in the workflow.
    /// </summary>
    public sealed class WorkflowAnalysis
    {
        private List<WorkflowException> errors = new List<WorkflowException>();

        /// <summary>
        /// Default constructor.
        /// </summary>
        internal WorkflowAnalysis()
        {
        }

        /// <summary>
        /// Gets the number of states in the workflow.
        /// </summary>
        public int StateCount
        {
            get;
            internal set;
        }

        /// <summary>
        /// Gets the number of transitions in the workflow.
        /// </summary>
        public int TransitionCount
        {
            get;
            internal set;
        }

        /// <summary>
        /// Gets the collection of errors found in the workflow
        /// during analysis.
        /// </summary>
        public IEnumerable<WorkflowException> Errors
        {
            get { return this.errors; }
        }

        /// <summary>
        /// Gets a flag indicating whether or not the analysis
        /// unconvered any errors in the workflow.
        /// </summary>
        public bool HasErrors
        {
            get { return (this.errors.Count > 0); }
        }

        internal void AddError(WorkflowException error)
        {
            this.errors.Add(error);
        }
    }
}
